domotic.connection_fail = Невозможно подключиться к устройству со следующим адресом: %s
